"""PDF health report generator using WeasyPrint."""

import logging
from datetime import datetime
from io import BytesIO
from typing import Any, Optional

logger = logging.getLogger(__name__)

REPORT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 10px; }
    h2 { color: #16213e; margin-top: 30px; }
    .header { display: flex; justify-content: space-between; align-items: center; }
    .grade { font-size: 48px; font-weight: bold; padding: 20px; border-radius: 10px;
             text-align: center; width: 100px; }
    .grade-a { background: #d4edda; color: #155724; }
    .grade-b { background: #fff3cd; color: #856404; }
    .grade-c { background: #ffeaa7; color: #856404; }
    .grade-d { background: #f8d7da; color: #721c24; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { padding: 8px 12px; border: 1px solid #ddd; text-align: left; }
    th { background: #f8f9fa; }
    .status-clean { color: #155724; font-weight: bold; }
    .status-warning { color: #856404; font-weight: bold; }
    .status-danger { color: #721c24; font-weight: bold; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd;
              font-size: 12px; color: #666; }
</style>
</head>
<body>
    <div class="header">
        <div>
            <h1>iDiag Health Report</h1>
            <p><strong>{{ device.model or 'Unknown Model' }}</strong> &mdash;
               iOS {{ device.ios_version or 'N/A' }}</p>
            <p>Serial: {{ device.serial or 'N/A' }} &bull;
               IMEI: {{ device.imei or 'N/A' }}</p>
        </div>
        <div class="grade grade-{{ grade_class }}">{{ grade or 'N/A' }}</div>
    </div>

    <h2>Battery</h2>
    <table>
        <tr><th>Health</th><td>{{ battery_health }}%</td></tr>
        <tr><th>Cycle Count</th><td>{{ battery_cycles }}</td></tr>
    </table>

    <h2>Parts Originality</h2>
    <table>
        <tr><th>All Original</th><td>{{ 'Yes' if parts_original else 'No' }}</td></tr>
        {% if replaced_parts %}
        <tr><th>Replaced</th><td>{{ replaced_parts }}</td></tr>
        {% endif %}
    </table>

    <h2>Storage</h2>
    <table>
        <tr><th>Total</th><td>{{ storage_total }} GB</td></tr>
        <tr><th>Used</th><td>{{ storage_used }} GB</td></tr>
        <tr><th>Available</th><td>{{ storage_available }} GB</td></tr>
    </table>

    <h2>Verification</h2>
    <table>
        <tr><th>Blacklist</th>
            <td class="status-{{ 'clean' if blacklist == 'clean' else 'danger' }}">
                {{ blacklist }}</td></tr>
        <tr><th>Find My iPhone</th>
            <td class="status-{{ 'clean' if fmi == 'off' else 'danger' }}">
                {{ fmi }}</td></tr>
        <tr><th>Carrier</th><td>{{ carrier }}</td></tr>
        <tr><th>Carrier Lock</th>
            <td class="status-{{ 'warning' if carrier_locked else 'clean' }}">
                {{ 'Locked' if carrier_locked else 'Unlocked' }}</td></tr>
    </table>

    <div class="footer">
        <p>Generated by iDiag on {{ report_date }} &bull; UDID: {{ device.udid }}</p>
    </div>
</body>
</html>
"""


def generate_report_html(device: Any, diagnostics: Optional[Any] = None,
                         verification: Optional[Any] = None,
                         grade: str = "") -> str:
    """Render the HTML report template with device data."""
    from jinja2 import Template

    diag = diagnostics
    verif = verification
    grade_letter = grade[:1].upper() if grade else "N"
    grade_class = grade_letter.lower() if grade_letter in "ABCD" else "c"

    template = Template(REPORT_HTML_TEMPLATE)
    return template.render(
        device=device,
        grade=grade,
        grade_class=grade_class,
        battery_health=diag.battery.health_percent if diag else 0,
        battery_cycles=diag.battery.cycle_count if diag else 0,
        parts_original=diag.parts.all_original if diag else True,
        replaced_parts=", ".join(diag.parts.replaced_parts) if diag else "",
        storage_total=round(diag.storage.total_gb, 1) if diag else 0,
        storage_used=round(diag.storage.used_gb, 1) if diag else 0,
        storage_available=round(diag.storage.available_gb, 1) if diag else 0,
        blacklist=verif.blacklist_status if verif else "unknown",
        fmi=verif.fmi_status if verif else "unknown",
        carrier=verif.carrier if verif else "",
        carrier_locked=verif.carrier_locked if verif else False,
        report_date=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )


def generate_pdf(device: Any, diagnostics: Optional[Any] = None,
                 verification: Optional[Any] = None,
                 grade: str = "") -> bytes:
    """Generate PDF report bytes. Requires WeasyPrint."""
    html = generate_report_html(device, diagnostics, verification, grade)
    try:
        from weasyprint import HTML
        pdf_buffer = BytesIO()
        HTML(string=html).write_pdf(pdf_buffer)
        return pdf_buffer.getvalue()
    except ImportError:
        logger.error("WeasyPrint not installed — returning HTML as fallback")
        return html.encode("utf-8")
